### ISSUE TITLE
[Suggestion] Make "Avg. conf. rate" only average the transactions older than the "Avg. conf. time"

### ISSUE THREAD

**Issue by sloganking** [cyclux/tanglemonitor#10]
As seen in this photo

https://i.imgur.com/OV1QP2Z.png

When the "Avg. conf. time" is very long, the "Avg. conf. rate" indicator can display percentages that are lower than the actual chance of transactions getting confirmed.

Edit:

This margin of error decreases the more transactions you view and increases the less you view.

Here is an extreme example (taken around the same time as the photo above) that shows how the "Avg. conf. rate" indicator shows lower values than reality.

https://i.imgur.com/hSdj2dz.png

**Comment by cyclux** [comment]
@SleepingFox88 Good idea, will think about a solution.

**Comment by cyclux** [comment]
@SleepingFox88 Finally it's implemented as "Avg. effective conf. rate".
