### ISSUE TITLE
Suggestion: Let the user filter transactions by toggling the type labels.

### ISSUE THREAD

**Issue by ixuz** [cyclux/tanglemonitor#12]
Hi!

Screenshot: [Screenshot](https://puu.sh/ATGnr/04ae9be79c.png)
I have a suggestion that it would be natural to let the user filter transaction types by clicking/toggling the transaction type labels in my screenshot. That's it! :)

Best Regards,
Anton Wiklund

**Comment by cyclux** [comment]
@ixuz Thanks for your suggestion. It may be possible to do that but I can not really imagine which benefit / additional information do you get out such filtering? Specific transactions types typically provide analytical value if compared to the others.

**Comment by ixuz** [comment]
project deprecated, closing this issue. 🙃
