### ISSUE TITLE
feature : on mouse over, iota value of transaction

### ISSUE THREAD

**Issue by wonkytonky** [cyclux/tanglemonitor#4]
feature : on mouse over, iota value of transaction

**Comment by cyclux** [comment]
@wonkytonky Done, not the prettiest implementation but at least it's visiable for now ;)

**Comment by wonkytonky** [comment]
thanks .. that was fast. maybe another suggestion. if the tx has a value maybe give it a birhter  color of green or yellow.. ?   just brainstorming here. 

this way one can instantly find those value tx  without going over each  tx.

**Comment by cyclux** [comment]
@wonkytonky Have you seen the "Hize zero value transactions" option at the top right? I think about it to highlight value TX on the total view aswell. But I have to be careful not to overload the screen with information, getting very colorful already, and probably adding "red" for inconsistent bundles as well soon.
