### ISSUE TITLE
"minutes ago" goes into the negatives

### ISSUE THREAD

**Issue by sloganking** [cyclux/tanglemonitor#6]
https://i.imgur.com/T0F0kKm.png

This could have been because my system time was too far back. However upon fixing it, there is no change to the website.

**Comment by cyclux** [comment]
@SleepingFox88 Has this ever happened again to you? Could have been a glitch I fixed some days ago.

**Comment by cyclux** [comment]
Fixed

**Comment by sloganking** [comment]
@cyclux Seems to be fixed for me regardless of local system time now. Thanks!
