### ISSUE TITLE
Mainnet/Spamnet/Testnet switch

### ISSUE THREAD

**Issue by ericvrp** [cyclux/tanglemonitor#9]
In the top center it now says testnet/spamnet. Could this please be change to a dropdown for network selection?

**Comment by cyclux** [comment]
@ericvrp Sure, I already have planned this as part of a styling overhaul. However, can also do a quick and dirty interim solution. Maybe I'll get time tonight.

**Comment by cyclux** [comment]
@ericvrp Finally implemented.
